### ISSUE TITLE
Make autocompletion of Markdown files subfolder aware

### ISSUE THREAD

**Issue by woodworker** [kevgo/vscode-markdown-ide#3]
It would be great if (by config option or default) make the autocompletion aware of markdownfiles in subfolders

**Comment by kevgo** [comment]
Agreed! I hope to get to it in the next couple of days.

**Comment by kevgo** [comment]
@woodworker I have just released v0.0.4 that should fix this issue. Please give it a try and let me know if you run into any other issues!
